### ISSUE TITLE
Versions of modules in read.me

### ISSUE THREAD

**Issue by polyccon** [foundersandcoders/ws-tdd-node-server#34]
Some students were getting an error about "test exited without finishing", and so we stopped everyone and asked them to update their versions of shot and tape as per the ones in the package.json of the solution and that solved the problem.
Perhaps it should be added in the readme that they need to make sure to install the up-to-date versions.

**Comment by eliascodes** [comment]
This is because versions of shot > 4.0 exclusively use a promise interface.

This is pretty annoying, since it means we'd either have to introduce promises before this workshop, or change install instructions to something like
```
npm i -D shot@3.4
```
The latter is obviously easiest, but requires explanation and justification.

**Comment by idantb101** [comment]
should we re-think using shot, maybe replacing it with supertest if we need to use the specific old version?

**Comment by eliascodes** [comment]
@idantb101 yeah, that's another possibility, possibly a better option than either of the above.

**Comment by m4v15** [comment]
@njseeto 

```js
test('Home route', (t) => {
  shot.inject(router, { method: 'get', url: '/' }, (res) => {
    t.equal(res.statusCode, 200, 'should respond with status code of 200');
    t.equal(res.payload, 'Hello', 'response should contain \'Hello\'');
    t.end();
  })

  supertest(server)
    .get('/')
    .end((err, res) => {
      
    })

})
```

www.github.com/foundersandcoders/open-tourism-platform

**Comment by njseeto** [comment]
@m4v15 Thanks! Got it running 🏃  🏃

**Comment by m4v15** [comment]
@polyccon you happy to close this now shot has been replaced with supertest?

**Comment by njseeto** [comment]
Will also need to change the name of the repo from tdd-node-server-with-shot-and-tape to tdd-node-server-with-supertest-and-tape and also the repo description. Thank you!

**Comment by eliascodes** [comment]
Renamed and PR opened to update links. Closing.
