### ISSUE TITLE
Tips for mentoring link dead

### ISSUE THREAD

**Issue by martinbagshaw** [foundersandcoders/ws-tdd-node-server#39]
https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/tips-for-mentoring.md returns a 404

**Comment by oliverjam** [comment]
I assume this is the correct link

https://github.com/foundersandcoders/master-reference/blob/master/coursebook/mentorship/mentorship-techniques.md

**Comment by oliverjam** [comment]
Actually I don't understand why that's linked where it is ("when you're pairing") since it contains zero info about pairing
